name: 'GoChat CI/CD'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '!.github/**' # Ignore changes to workflow files

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run tests with Make
      run: make test
      
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Build with Make
      run: make build
    
    - name:  Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActions-Packer
        aws-region: us-east-1
      
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      run: "packer init packer/gochat.pkr.hcl"

    - name: Run `packer validate`
      id: validate
      run: "packer validate packer/gochat.pkr.hcl"
      env:
        PKR_VAR_domain_name: ${{ vars.DOMAIN_NAME }}

    - name: Run `packer build`
      id: build
      run: "packer build -color=false -on-error=abort packer/gochat.pkr.hcl"
      env:
        PKR_VAR_domain_name: ${{ vars.DOMAIN_NAME }}

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name:  Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActions-Terraform
        aws-region: us-east-1
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Format
      run: terraform -chdir=terraform fmt -check

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      id: plan
      run: terraform -chdir=terraform plan -no-color -input=false 2>&1
      continue-on-error: true
      env:
        TF_VAR_signing_key: ${{ secrets.SIGNING_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_acm_certificate_domain: ${{ secrets.ACM_CERTIFICATE_DOMAIN }}
        TF_VAR_route53_zone_id: ${{ secrets.ROUTE53_ZONE_ID }}

    - name: Write TF Plan to PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      env:
        PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
      with:
        script: |
          const {data: comments} = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });

          // Remove old Terraform comments
          const oldComments = comments.filter(comment => comment.body.startsWith('## Terraform Plan'));
          for (const comment of oldComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id
            });
          }

          const planOutput = process.env.PLAN_OUTPUT;
          const comment = `## Terraform Plan\n\`\`\`\n${planOutput}\n\`\`\``;
          const prNumber = context.payload.pull_request.number;
          await github.rest.issues.createComment({
            ...context.repo,
            issue_number: prNumber,
            body: comment
          });

    - name: Check For Plan Error
      if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform -chdir=terraform apply -no-color -input=false -auto-approve
      env:
        TF_VAR_signing_key: ${{ secrets.SIGNING_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_acm_certificate_domain: ${{ secrets.ACM_CERTIFICATE_DOMAIN }}
        TF_VAR_route53_zone_id: ${{ secrets.ROUTE53_ZONE_ID }}
